---
- src: https://github.com/KEAOSolutions/ansible-audit-hardening.git
  version: 0.0.2
  name: audit-hardening

- src: https://github.com/dogbonnahNB/ansible-os-hardening.git
  version: 3.1.0.6
  name: os-hardening

- src: https://github.com/KEAOSolutions/ansible-ssh-hardening
  version: 3.1.0.1
  name: ssh-hardening

- src: https://github.com/KEAOSolutions/ansible-docker
  version: 0.0.2
  name: docker

- src: https://github.com/KEAOSolutions/ansible-virtualbox
  version: v1.0.1
  name: virtualbox

- src: https://github.com/KEAOSolutions/ansible-role-firewall
  version: 0.2.2
  name: iptables

- src: https://github.com/KEAOSolutions/ansible-grub_cmdline.git
  version: v1.0.2
  name: grub-cmdline

- src: https://github.com/KEAOSolutions/ansible-role-clamav.git
  version: v0.1.4
  name: clamav

- src: https://github.com/KEAOSolutions/ansible-fstab.git
  version: v0.0.1
  name: fstab
